# Generated by Django 4.2.10 on 2024-03-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "operacion",
                    models.CharField(
                        choices=[("+", "Suma"), ("-", "Resta")], max_length=2
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Movimiento",
                "verbose_name_plural": "Tipos de Movimientos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_soli", models.DateField()),
                ("descripcion", models.TextField()),
                ("recipe", models.ImageField(upload_to="recipes/")),
                (
                    "proceso_actual",
                    models.CharField(
                        choices=[
                            ("AD", "Administrador"),
                            ("AL", "Almacenista"),
                            ("AT", "Atención al Cliente"),
                        ],
                        default="AT",
                        max_length=2,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PR", "En Proceso"),
                            ("AP", "Aprobado"),
                            ("EE", "En Espera de Entrega"),
                            ("ET", "Entregado"),
                            ("RE", "Rechazado"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "tipo_solicitud",
                    models.CharField(
                        choices=[("ON", "En línea"), ("PR", "Presencial")], max_length=2
                    ),
                ),
                (
                    "beneficiado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.beneficiado",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Medicamento",
                "verbose_name_plural": "Solicitud de Medicamentos",
                "ordering": ["fecha_soli"],
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encargados", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "proceso_actual",
                    models.CharField(
                        choices=[("AD", "Administrador")], default="AD", max_length=2
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PR", "En Proceso"),
                            ("AP", "Aprobado"),
                            ("RE", "Rechazado"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "jefe_comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada",
                "verbose_name_plural": "Jornadas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "tipo_ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movimientos.tipomov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_mov", models.DateField(auto_now_add=True)),
                ("cantidad", models.IntegerField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="inventario.inventario",
                    ),
                ),
                (
                    "tipo_mov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movimientos.tipomov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="DetalleJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cant_solicitada", models.IntegerField()),
                ("cant_aprobada", models.IntegerField()),
                (
                    "beneficiado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.beneficiado",
                    ),
                ),
                ("productos", models.ManyToManyField(to="inventario.producto")),
            ],
            options={
                "verbose_name": "Detalle de Jornada",
                "verbose_name_plural": "Detalle de Jornadas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DetalleIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("lote", models.CharField(max_length=50)),
                ("f_vencimiento", models.DateField()),
                (
                    "ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalle",
                        to="movimientos.ingreso",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de ingreso",
                "verbose_name_plural": "Detalles de ingresos",
            },
        ),
        migrations.CreateModel(
            name="DetalleSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cant_solicitada", models.IntegerField(default=1)),
                ("cant_entregada", models.IntegerField(default=0)),
                ("inventario", models.ManyToManyField(to="inventario.inventario")),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de solicitud",
                "verbose_name_plural": "Detalle de solicitudes",
                "ordering": ["pk"],
                "unique_together": {("solicitud", "producto")},
            },
        ),
    ]
